### PR TITLE
FIX Set the invalid prop when errorMessage - SS4

### PR DESCRIPTION
**Pull request by emteknetnz**
Fixes https://github.com/silverstripe/silverstripe-security-extensions/issues/15

SS3 PR https://github.com/silverstripe/silverstripe-security-extensions/pull/35

**Before**
image

**After**
image

### CODE REVIEW

**Comment by robbieaverill** [comment]
Can you test throw from the modal context as well? I think there were two ways this renders and the validation styles weren't showing up in one or the other

**Comment by emteknetnz** [comment]
@robbieaverill I'm not personally familiar with the modal context, what steps do I need to take to get sudo mode to show in a modal?

**Comment by robbieaverill** [comment]
I think if you're an admin user you can manage MFA settings for other members, which opens in a modal

**Comment by emteknetnz** [comment]
@robbieaverill I just tried this, though it does not render in modal.  Managing MFA settings for other users appears to be the same as managing them for yourself.

**Comment by Cheddam** [comment]
@robbieaverill Any chance you could boot this up and provide an example? I'm struggling to recall this being used in any context outside of the MFA settings field 🤔

**Comment by robbieaverill** [comment]
Yeah will do, sorry

**Comment by robbieaverill** [comment]
Ok I had a look and I think I'm mistaken. The field is used exclusively on RegisteredMFAMethodListField, which is used in your own profile as well as any member's profile you view.

This patch does fix the problem in SilverStripe 4.4 and up, but it's really just flipping the problem around - it is now broken in 4.3 and below.

My recommendation would be to either make this target a new minor release and bump the minimum core requirement to admin ^1.4, or work out how to fix this problem for all versions.

**Comment by emteknetnz** [comment]
Would it still work in 4.3 if we changed it to `{ valid:false, invalid: true }`?

**Comment by robbieaverill** [comment]
Worth a try!

**Comment by emteknetnz** [comment]
@robbieaverill yup works :-)

SS 4.3
image

SS 4.6
image

**Review by robbieaverill — APPROVED** [review]

**Pull request merged**
