### PR TITLE
be consistent in wording and grammatically correct with regards to 'log in'

### PR DESCRIPTION
**Pull request by NightJar**
Ref. https://github.com/silverstripe/silverstripe-mfa/issues/220

### CODE REVIEW

**Comment by robbieaverill** [comment]
Is this a subtask of silverstripe/silverstripe-mfa#220?

**Comment by NightJar** [comment]
Yes, however please hold on merging as the jury is still out.

**Comment by NightJar** [comment]
@newleeland any news/consensus on this change to your set of changes?
i.e. "Login" should be "Log in"

**Comment by robbieaverill** [comment]
Confirmed, two words

**Pull request merged**
