### PR TITLE
FIX Unique identifier field for Member is used as the authentication data key instead of Email hardcoded

### LINKED ISSUE #18: Sudo mode check relies on "Email" as the name of the unique identifier for users
In the backported 3.0 branch it's always assumed that `Email` is the field to use for the unique identifier. Came up as we've been implementing the `activedirectory` module which uses `Login` as the form field name, as it's possible for a user to log in using their email or LDAP username.

https://github.com/silverstripe/silverstripe-security-extensions/blob/3.0/src/Control/SudoModeController.php#L129

We're implementing our own version of this controller, however it'd still be an issue for out-of-the-box installations that are using the CMS with an custom authenticator. Not sure the best solution as there's no solid API in SS3 for specifiying the name of the form field for the unique identifier (up to the implementation of `$authenticator::authenticate($authenticationData)` to read the passed in array)

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes #18

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Given @indygriffiths comment about the required details actually being defined by `Authenticator::authenticate` maybe it's a good idea to put an extension point here for other people who may need specific attributes set in this array?

**Comment by robbieaverill** [comment]
You want to put an extension point in a private method? You radical!

**Comment by robbieaverill** [comment]
How about if we put `$authenticationData` into a protected method, and extend from that?

**Comment by ScopeyNZ** [comment]
Sure I like that better :)

**Review by ScopeyNZ — APPROVED** [review]

**Pull request merged**
